### ISSUE TITLE
Different file size compared to original SS font

### ISSUE THREAD

**Issue by vanthome** [topcoat/fonts#5]
Hi,
if I compare the file sizes of the original font files from [here](http://sourceforge.net/projects/sourcesans.adobe/files/)
they differ.
Why is that?

**Comment by GarthDB** [comment]
Sorry, just dusting things off here and getting things working again. The fonts have been taken down from source forge and are on [github](https://github.com/adobe-fonts/source-sans-pro).

What were you noticing about the size?

**Comment by GarthDB** [comment]
Issue moved to [topcoat/topcoat #515](https://github.com/topcoat/topcoat/issues/515) via [**ZenHub**](https://www.zenhub.com/)

**Comment by GarthDB** [comment]
@vanthome I moved this issue and am closing the issues on this repo, it makes it hard to keep track of all of these when they are spread out across all these different projects.
